import { StrictMode, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = 'http://localhost:8000/api';

function download(blob, name) { const url = URL.createObjectURL(blob); const a = Object.assign(document.createElement('a'), { href: url, download: name }); a.click(); URL.revokeObjectURL(url); }
function App() {
  const input = useRef(); const [file, setFile] = useState(); const [info, setInfo] = useState(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function inspect(next) { setError(''); setInfo(); if (!next) return; if (!/\.xls(x)?$/i.test(next.name)) return setError('Choose an Excel .xlsx or .xls file.'); setFile(next); setBusy(true); const body = new FormData(); body.append('file', next); try { const r = await fetch(`${API}/inspect`, { method: 'POST', body }); const data = await r.json(); if (!r.ok) throw new Error(data.detail?.message || data.detail || 'We could not read this file.'); setInfo(data); } catch (e) { setError(e.message); setFile(); } finally { setBusy(false); } }
  async function generate() { setBusy(true); setError(''); const body = new FormData(); body.append('file', file); try { const r = await fetch(`${API}/generate`, { method: 'POST', body }); if (!r.ok) { const d = await r.json(); throw new Error(d.detail?.message || d.detail || 'Generation failed.'); } download(await r.blob(), 'payment_slips.zip'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function one(workOrder) { setBusy(true); const body = new FormData(); body.append('file', file); try { const r = await fetch(`${API}/work-order-pdf?work_order=${encodeURIComponent(workOrder)}`, { method: 'POST', body }); if (!r.ok) throw new Error('Unable to create that PDF.'); download(await r.blob(), `${workOrder.replace(/[\\/:*?"<>|]/g, '-')}.pdf`); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <main><section className="hero"><p className="eyebrow">DOCUMENT UTILITY</p><h1>Payment Slip Generator</h1><p>Upload your FORM-XVII Excel file. We group every employee by Work Order and create ready-to-download PDFs.</p></section><section className="card"><h2>1. Upload your Excel file</h2><input ref={input} className="sr" id="upload" type="file" accept=".xlsx,.xls" onChange={e => inspect(e.target.files?.[0])}/><label className="dropzone" htmlFor="upload" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); inspect(e.dataTransfer.files?.[0]); }}><strong>Drop your Excel file here</strong><span>or choose a .xlsx or .xls file from your computer</span><b>Choose Excel file</b></label>{busy && <p className="status" role="status">Reading your file and preparing payment slips…</p>}{error && <p className="error" role="alert">{error}</p>}{info && <><div className="summary"><div><strong>{file.name}</strong><span>Excel file ready</span></div><div><strong>{info.records}</strong><span>payment slips found</span></div><div><strong>{info.workOrders}</strong><span>Work Orders found</span></div></div><h2>2. Generate and download</h2><button className="primary" disabled={busy} onClick={generate}>Download all PDFs as ZIP</button><div className="orders">{info.orders.map(x => <button key={x.workOrder} disabled={busy} onClick={() => one(x.workOrder)}><span>{x.workOrder}<small>{x.records} payment slips</small></span><small>Download PDF</small></button>)}</div></>}</section><footer>Your information is processed only while the file is being generated.</footer></main> }
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
